:doctitle: 1.BasicDataTypes/1.FindTheRunnerUpScore
:author: Jerod Gawne
:email: jerodgawne@gmail.com
:docdate: June 11, 2018
:revdate: {docdatetime}
:src-uri: https://github.com/jerodg/hackerrank

:difficulty: easy
:time-complexity: low
:required-knowledge: list, data structures
:advanced-knowledge:
:solution-variability: 1
:score: 10
:keywords: python, {required-knowledge}, {advanced-knowledge}
:summary: Given the participants' score sheet for your University Sports Day, you are required to find the runner-up score. You are given scores. Store them in a list and find the score of the runner-up.

:doctype: article
:sectanchors:
:sectlinks:
:sectnums:
:toc:

{summary}

== Learning

https://docs.python.org/3.7/tutorial/datastructures.html[PyDocs - Data Structures]

== Tutorial

=== Slice Notation
// todo: improve tutorial
.It's pretty simple really
[source,python,linenums]
a[start:end] # items start through end-1
a[start:]    # items start through the rest of the array
a[:end]      # items from the beginning through end-1
a[:]         # a copy of the whole array

There is also the step value, which can be used with any of the above:

[source,python,linenums]
a[start:end:step] # start through not past end, by step

The key point to remember is that the :end value represents the first value that is not in the selected slice.
So, the difference beween end and start is the number of elements selected (if step is 1, the default).

The other feature is that start or end may be a negative number, which means it counts from the end of the array instead of the beginning.

.So
[source,python,linenums]
a[-1]    # last item in the array
a[-2:]   # last two items in the array
a[:-2]   # everything except the last two items

.Similarly, step may be a negative number
[source,python,linenums]
a[::-1]    # all items in the array, reversed
a[1::-1]   # the first two items, reversed
a[:-3:-1]  # the last two items, reversed
a[-3::-1]  # everything except the last two items, reversed

Python is kind to the programmer if there are fewer items than you ask for.
For example, if you ask for a[:-2] and a only contains one element, you get an empty list instead of an error.
Sometimes you would prefer the error, so you have to be aware that this may happen.

== Improving the Template

=== Convention

.Missing
* shebang
* encoding
* doc-comments

=== Extraneous

// todo: define this better in an ::include:: file and include it here .Unnecessary variable definition
* The first _n = int(input())_ is only necessary to pass the challenge, it is, however, entirely unnecessary in python.
** Knowing the number of inputs is a head of time is just not needed as python can easily manipulate a string of input using input.split() and we can call len() later if we really need to know how many.

=== Pep8

N/A

=== Syntax

N/A

== Reference

https://www.hackerrank.com/challenges/find-second-maximum-number-in-a-list[Hackerrank - Find the Runner Up Score]
https://stackoverflow.com/a/509295/4434405[Stack Overflow - Greg Hewgill]
