:author: Jerod Gawne
:email: jerodgawne@gmail.com
:docdate: March 06, 2019
:revdate: {docdatetime}
:src-uri: https://github.com/jerodg/hackerrank

:difficulty: medium
:time-complexity: low
:required-knowledge:
:solution-variability: 3
:score: 30
:keywords: python, {required-knowledge}
:summary:

:doctype: article
:sectanchors:
:sectlinks:
:sectnums:
:toc:
= 06.Collections/05.MostCommon (Company Logo)

A newly opened multinational brand has decided to base their company logo on the three most common characters in the company name.
They are now trying out various combinations of company names and logos based on this condition.
Given a string , which is the company name in lowercase letters, your task is to find the top three most common characters in the string.

Print the three most common characters along with their occurrence count.
Sort in descending order of occurrence count.
If the occurrence count is the same, sort the characters in alphabetical order.

== Learning

== Tutorial

This can be solved by using Python counters or counting sort.

Approach:

STEP 1: Create a list, letters, of size . Initialize each element to .

STEP 2: Traverse through the input string . If a character in the string is 'a', then increment letter by . If 'b' is found, then increment letter by and so on.

STEP 3: Now run a loop three times.
Inside the loop, store the maximum value of letters in the variable max_letter.

STEP 4:.
In the scope of the previous loop, run another loop and find the index of the first occurrence of max_letter.
Now, print the appropriate letter associated with that index and the max_letter.

== The Problem
// todo: state as agile story
=== Objective

=== Deliverables

==== Input

===== Constraints

==== Output

===== Constraints

=== Constraints

=== Bonus

=== Breakdown

== Improving the Problem
// todo: improving the problem

== Improving the Template

=== Convention

.Missing
* shebang
* encoding
* doc-comments

=== Extraneous

N/A

=== Pep8

* No new-line at end of file

=== Syntax

N/A

== Improving the Tests
// todo: improving the tests

== Reference
