:author: Jerod Gawne
:email: jerodgawne@gmail.com
:docdate: February 03, 2020
:revdate: {docdatetime}
:src-uri: https://github.com/jerodg/hackerrank

:difficulty: medium
:time-complexity: medium
:required-knowledge: collections
:solution-variability: moderate
:score: 50
:keywords: python, {required-knowledge}
:summary:

:doctype: article
:sectanchors:
:sectlinks:
:sectnums:
:toc:
:source-highlighter: rouge
:listing-caption: Listing

= 07.Piling Up
{summary}
There is a horizontal row of  cubes. The length of each cube is given. You need to create a new vertical pile of cubes. The new pile should follow these directions: if  is on top of  then .

When stacking the cubes, you can only pick up either the leftmost or the rightmost cube each time.
Print "Yes" if it is possible to stack the cubes.
Otherwise, print "No".
Do not print the quotation marks.

Input Format

The first line contains a single integer , the number of test cases.
For each test case, there are lines.
The first line of each test case contains , the number of cubes.
The second line contains space separated integers, denoting the sideLengths of each cube in that order.

Constraints

Output Format

For each test case, output a single line containing either "Yes" or "No" without the quotes.

Sample Input

2 6 4 3 2 1 3 4 3 1 3 2 Sample Output

Yes No Explanation

In the first test case, pick in this order: left - , right - , left - , right - , left - , right - .
In the second test case, no order gives an appropriate arrangement of vertical cubes. will always come after either or .
== Learning

== Tutorial
// todo: tutorial

== The Problem
// todo: state as agile story
=== Objective

=== Deliverables

==== Input

===== Constraints

==== Output

===== Constraints

=== Constraints

=== Bonus

=== Breakdown

== Improving the Problem
// todo: improving the problem

== Improving the Template

=== Convention

.Missing
* shebang
* encoding
* doc-comments

=== Extraneous

N/A

=== Pep8

* No new-line at end of file

=== Syntax

N/A

== Improving the Tests
// todo: improving the tests

== Reference
