[project]
name = "python-code-challenges"
version = "0.1.0"
description = "Python Code Challenges"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sortedcontainers>=2.4.0",
]

[dependency-groups]
dev = [
    "ruff>=0.9.7",
    "pytest>=8.3.4",
    "pytest-mock>=3.14.0",
    "pytest-cov>=6.0.0",
]

[tool.ruff]
unsafe-fixes = true
extend-include = ["*.ipynb"]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    ".idea",
    ".venv",
]
line-length = 132
fix = true
indent-width = 4
target-version = "py313"
include = ["*.py"]
respect-gitignore = true
select = [
    "F", # pyflakes
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "C901", # mccabe complexity
    "I", # isort
    "N", # pep8-naming
    "D", # pydocstyle
    "YTT", # flake8-2020
    "ANN", # flake8-annotations
    "ASYNC", # flake8-async
    "A", # flake8-builtins
    "COM", # flake8-commas
    "CPY", # flake8-copyright
    "C4", # flake8-comprehensions
    "DTZ", # flake8-datetimez
    "ICN", # flake8-import-conventions
    "INP", # flake8-no-pep420
    "PIE", # flake8-pie
    "PT", # flake8-pytest-style
    "Q", # flake8-quotes
    "RSE", # flake8-raise
    "RET", # flake8-return
    "SLF", # flake8-self
    "SLOT", # flake8-slot
    "SIM", # flake8-simplify
    "TID", # flake8-tidy-imports
    "INT", # flake8-gettext
    "ARG", # flake8-unused-arguments
    "PTH", # flake8-use-pathlib
    "TD", # flake8-todos
    "FIX", # flake8-fixme
    "ERA", # eradicate
    "PD", # pandas-vet
    "PL", # pylint
    "FLY", # flynt
    "PERF", # perflint
    "FURB", # refurb
    "RUF", # ruff
]
ignore = ["T201", # print statements
    "CPY001", # missing-copyright-notice (doesn't "see" the current notice for some reason)
    "PLR2004", # Magic value used in comparison
    "N999", # No name in module (or numbers as name)
    "COM812", # No trailing comma
]
preview = true
task-tags = ["TODO:", "todo:", "FIXME:", "fixme:"]
fixable = ["ALL"]
unfixable = ["T20"]
extend-fixable = []

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.pycodestyle]
max-doc-length = 132

[tool.ruff.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"

[tool.ruff.lint.isort]
case-sensitive = true
combine-as-imports = true
order-by-type = true
no-sections = false
known-first-party = []
section-order = ["future", "standard-library", "first-party", "local-folder", "third-party"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
line-ending = "lf"
docstring-code-format = true
docstring-code-line-length = 132
preview = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]
markers = ["random: marks tests as random (deselect with '-m \"not random\"')"]
