:doctitle: 2.Strings/12.TheMinionGame
:author: Jerod Gawne
:email: jerodgawne@gmail.com
:docdate: June 28, 2018
:revdate: {docdatetime}
:src-uri: https://github.com/jerodg/hackerrank

:difficulty: moderate
:time-complexity: moderate
:required-knowledge: input and output, control flow
:solution-variability: 1
:score: 40
:keywords: python, {required-knowledge}
:summary: Kevin and Stuart want to play the 'The Minion Game'.

:doctype: article
:sectanchors:
:sectlinks:
:sectnums:
:toc:

{summary}

== Learning

* https://docs.python.org/3.7/tutorial/inputoutput.html[PyDocs - Input and Output]
* https://docs.python.org/3.7/tutorial/controlflow.html[PyDocs - Control Flow]

== Tutorial
// todo: tutorial
This challenge can be solved by finding all the substrings of the string and separating the substrings on the basis of their first character.

If the string is BANANA, the substrings are:

B BA BAN BANA BANAN BANANA A AN ANA ANAN ANANA N NA NAN NANA A AN ANA N NA A It is interesting to note that in BANANA:

Words formed using the first letter B = 6 Words formed using the second letter A = 5 Words formed using the third letter N = 4 Words formed using the fourth letter A = 3 Words formed using the fifth letter N = 2 Words formed using the last letter A = 1

Using this pattern, you can run a loop from the start to the end of the string and filter out words starting with vowels and consonants.

See problem tester's code to learn more.

.Several optimizations (solution.py)
Use frozenset for the vowels.
This is the fastest to lookup in.
Iterate through characters instead of indexing Iterate q reverse to avoid a subtraction in each sum Avoid repeated calls to len Only calculate Kevins score the hard way.
Use the fact that the total number of substrings is n * (n + 1) / 2 and find Stuart's score by subtracting Kevin's from the total number of substrings.

== The Problem
// todo: state as agile story
=== Objective

=== Deliverables

==== Input

===== Constraints

==== Output

===== Constraints

=== Constraints

=== Bonus

=== Breakdown

== Improving the Problem
// todo: improving the problem

== Improving the Template

=== Convention

.Missing
* shebang
* encoding
* doc-comments
* pass in empty function

=== Extraneous

N/A

=== Pep8

* No new-line at end of file
* Expecting two lines before function declaration

=== Syntax

N/A

== Improving the Tests
// todo: improving the tests

== Reference

* https://www.hackerrank.com/challenges/the-minion-game[Hackerrank - The Minion Game]
* https://www.hackerrank.com/challenges/the-minion-game/forum/comments/321567[Hackerrank - Comment]
